language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
before_install:
  - sudo add-apt-repository -y ppa:samrog131/ppa
  - sudo apt-get update
  - sudo apt-get -y install wget tar bzip2 flvtool2 ffmpeg-real
  - wget http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz
  - tar zxf ffmpeg.static.64bit.latest.tar.gz
  - sudo cp ffmpeg ffprobe /usr/bin
  - export ALT_FFMPEG_PATH=$(pwd)/ffmpeg
  - export ALT_FFPROBE_PATH=$(pwd)/ffprobe
